FROM ghcr.io/ministryofjustice/hmpps-clamav:latest

USER "root"
RUN freshclam

# We run as UID 1000 in kubernetes, this will allow us to start the process
RUN mkdir -p /var/run/clamav && \
  chown -R 1000:1000 /var/run/clamav && \
  chown -R 1000:1000 /var/lib/clamav
USER 1000
