name: Twice daily build ClamAV with up-to-date virus DB
on:
  schedule:
    - cron:  '0 4/12 * * *'
env:
  REGISTRY: ghcr.io
jobs:
  build_scan_push:
    name: ClamAV-daily
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dockerfile-dir:
          - hmpps-clamav
    permissions:
      packages: write
      contents: read
      security-events: write
    steps:
      - name: Check out the repo
        uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7

      - name: Docker metadata
        id: meta
        uses: docker/metadata-action@dc802804100637a589fabce1cb79ff13a1411302 # v6.2.0
        with:
          images: ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.dockerfile-dir }}-freshclammed
          flavor: |
            latest=true
          tags: |
            type=schedule
            type=ref,event=branch
            type=ref,event=tag
            type=ref,event=pr
            type=sha
      - name: Log in to GitHub container registry
        uses: docker/login-action@af1e73f918a031802d376d3c8bbc3fe56130a9b0 # v4.4.0
        with:
          registry: ${{ env.REGISTRY }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build container image
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: ./${{ matrix.dockerfile-dir }}/Dockerfile.freshclammed
          context: ./${{ matrix.dockerfile-dir }}
          pull: true
          push: false
          tags: |
            ${{ env.REGISTRY }}/${{ github.repository_owner }}/${{ matrix.dockerfile-dir }}-freshclammed:${{ github.sha }}

      - name: Push container image to repository
        if: ${{ success() && github.ref == 'refs/heads/main' }}
        uses: docker/build-push-action@53b7df96c91f9c12dcc8a07bcb9ccacbed38856a # v7.3.0
        with:
          file: ./${{ matrix.dockerfile-dir }}/Dockerfile.freshclammed
          context: ./${{ matrix.dockerfile-dir }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
          push: true

      - name: Slack notification
        id: slack
        if: ${{ failure() }}
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          channel-id: ${{ secrets.SLACK_GITHUB_ALERTS }}
          slack-message: "_Job:_ ${{ github.job }}\n_Status:_ ${{ job.status }}\n_Workflow:_ ${{ github.workflow }}\n_Repo:_ ${{ github.repository }}\n<https://github.com/${{github.repository}}/actions/runs/${{github.run_id}}|View on github>\n"
        env:
          SLACK_BOT_TOKEN: ${{ secrets.HMPPS_SLACK_BOT_TOKEN }}
